vof/compute.tf

Changes update_strategy from NONE to RESTART for instance_group_manager.
Changes update_strategy from NONE to RESTART for instance_group_manager.
N/A
N/A
N/A
N/A
N/A

Changes update_strategy from NONE to RESTART for instance_group_manager.

---

docs/maintenance.md
packer/start_vof.sh
vof/compute.tf
vof/variables.tf
vof_base_image/setup.sh

Add features meant to handle VOF system maintenance. 
The crontab timing can be minimized to run the jobs and send notifications based on the specified time.
This is meant to handle system maintenance for the VOF project migration to GCP.

Vof maintenance

---

packer/start_vof.sh
vof/routing.tf

Add HTTP/HTTPS capability to the infrastructure
- Add HTTP/HTTPS capability to the infrastructure
- Restarts logging after log rotation has occurred by restarting the application through supervisord
N/A
N/A
N/A
N/A
N/A

Add HTTP/HTTPS capability to the infrastructure

---

packer/start_vof.sh
vof/compute.tf

This PR forwards all the http requests to https
- When a user accessed the app via any non-https connection, they are redirected to a safe https connection.
- Once deployed, just try accessing the site via http:// or fail to specify the protocol, you will automatically be redirected to https://
- This PR has a complimentary PR on the application repository [here.](https://github.com/andela/vof-tracker) It should be merged before the application is built for staging.
#154556674
N/A

#154556674 Forward all http requests to https

---

docs/infrastructure.md
packer/start_vof.sh

Run design v2 using staging environment
- Create a new environment variable to specify environment to run the application.
- If deployment environment is design-v2, use staging environment to run the application.
VOF tracker app has a new deployment for the new UI. The new deployment uses exactly the same configuration as the staging environment. This PR will ensure that while the new deployment is deployed to its own infrastructure environment, it runs in staging environment.
https://www.pivotaltracker.com/story/show/154919385

#154919385: Migrate design-v2 to GCP

---

docs/environment.md
docs/infrastructure.md
packer/start_vof.sh
vof/compute.tf
vof/variables.tf

add action cable configurations to different environments 
add redis-ip servers to the different environments
We want to integrate redis and configure action cable in our vof-tracker application .Redis will help in caching the information from the database  , and also work with action cable
N/A
This pr need to be merged before the VOF tracker pr is merged 
155650250

#155650250 Implement redis server and configure action cable

---

docs/environment.md
docs/infrastructure.md
packer/start_vof.sh
vof/compute.tf
vof/variables.tf

Start bugsnag in the vof application
Everytime there is a deployment the bugsnug should start 
So incase of any application errors there are reported on slack
N/A
[#155847357](https://www.pivotaltracker.com/story/show/155847357)

155847357  Set and start bugsnag in the application

---

packer/start_vof.sh

Seeds data into the table that have been created

#155770230: implement vof seeding

---

packer/start_vof.sh

It ensures that the API_URL, LOGIN_URL and LOGOUT_URL are using the proper platform endpoint in production
N/A
N/A
N/A
[#156632271](https://www.pivotaltracker.com/story/show/156632271)
N/A
N/A

#156632271: Ensure production environment uses platforms production endpoints

---

packer/start_vof.sh
vof/compute.tf

Reverts andela/vof-deployment-scripts#38

Revert "#156683073: Authorize specific ip addresses to access the database"

---

packer/start_vof.sh
vof/compute.tf

What does this PR do?
This pr specifies the specific Ip addresses that should access the database instance
Description of Task to be completed?
Currently any ip address can access the database instance given the password and database username
We want to only whitelist specific IP addresses to access the database for security reasons
How should this be manually tested?
N/A
Any background context you want to provide?
N/A
What are the relevant pivotal tracker stories?
#156683073
Screenshots (if appropriate)
N/A
Questions:

#156683073: Authorize specific ip addresses to access the database

---

vof/compute.tf
vof/redis.tf

- Uses internal redis instance IP for communication on the infrastructure
N/A
N/A
N/A
[#155931351](https://www.pivotaltracker.com/story/show/155931351)
N/A
N/A

#155931351: Automate redis server creation (fix)

---

packer/start_vof.sh

Ensures both master and replica SQL instances' authorized networks are updated during rolling updates.
N/A
N/A
N/A
[#156798951](https://www.pivotaltracker.com/story/show/156798951)
N/A
N/A

#156798951: Update replica SQL instance's authorized IPs

---

vof/database.tf

Make the databases highly available incase of failovers a new database end point is spin up immediately
N/A
N/A
N/A
155931326
N/A

155931326: Make the database  to be highly available

---

packer/start_vof.sh

Adds the NY office to the list of whitelisted IP addresses
N/A
N/A
N/A
[#156972043](https://www.pivotaltracker.com/story/show/156972043)
N/A
N/A

#156972043: Add NY office to authorized IPs

---

packer/start_vof.sh

This PR whitelists IPs used by the data engineering
team through a service called Jitterbit to access the
vof production db.
N/A
N.A
N/A
[#157477889](https://www.pivotaltracker.com/n/projects/2126505/stories/157477889)
N/A
N/A

#157477889: Whitelist Jitterbit service IPs

---

packer/start_vof.sh

- adds a fix to prevent downtime during deployments
N/A
N/A
N/A
N/A
N/A
N/A

#156542659: Ensure staging changes apply to production environment

---

packer/start_vof.sh
vof/compute.tf
vof/variables.tf

This PR adds google cloud storage credentials that will be used
when retrieving images from the `alc-profile-pictures` bucket
N/A
N/A
This PR enables this story to work as expected
[#156610575](https://www.pivotaltracker.com/n/projects/1959089/stories/156610575)
[#157960400](https://www.pivotaltracker.com/n/projects/1959089/stories/157960400)
N/A
N/A

#157960400: Add google cloud storage credentials

---

.gitignore
elk-infrastructure/compute.tf
elk-infrastructure/main.tf
elk-infrastructure/network.tf
elk-infrastructure/variables.tf
packer/packer.json
packer/setup-scripts/setup_filebeat.sh
packer/setup-scripts/setup_metricbeat.sh
packer/start_vof.sh
vof-elk-image/packer.json
vof-elk-image/setup.sh
vof-elk-image/start_elk.sh
vof/.gitignore
vof/network.tf

It creates the ELK infrastructure automatically on every VOF deployment using terraform. This is done with a custom made elk image that is also a part of this PR.
N/A
N/A
This PR should be merged only after [this one](https://github.com/andela/vof-deployment-scripts/pull/53). This is because the elk setup requires the new network restrictions put in place by it.
[#157840405](https://www.pivotaltracker.com/story/show/157840405)
N/A
N/A

157840405: Setup elk infrastructure automatically

---

packer/setup-scripts/setup_filebeat.sh
vof-elk-image/setup.sh
vof-elk-image/start_elk.sh

- fix filebeat yaml configuration
- setup elasticsearch curator to delete
log file indexes older than 30 days
every month with a cron job
N/A
N/A
N/A
[#158027985](https://www.pivotaltracker.com/story/show/158027985)
N/A
N/A

ch(logs): Setup curator and delete logs automatically

---

jenkins/.gitignore
jenkins/jenkins_instance.tf
jenkins/main.tf
jenkins/network.tf
jenkins/variables.tf
jenkins_packer/ansible_playbook_master.yml
jenkins_packer/packer_master_config.json
login-micro-service/database.tf
login-micro-service/main.tf
login-micro-service/outputs.tf
login-micro-service/variables.tf

- Add terraform files that creates mirco-login infrastructure
N/A
N/A
N/A
[158146077](https://www.pivotaltracker.com/story/show/158146077)
N/A
N/A

#158146077: Setup micrologin service infrastructure

---

packer/start_vof.sh

- add environment variables to enable integration of login
microservice for staging and production
N/A
N/A
N/A
[#158576695](https://www.pivotaltracker.com/story/show/158576695)
N/A
N/A

#158576695 Update application.yml file

---

packer/backup.sh
packer/packer.json
packer/post_backup_to_slack.sh
packer/start_vof.sh
vof_base_image/setup.sh

- install postgres 9.6 to match whats on the google sql instances.
- create .pgpass file to store backup credentials.
- create post_backup_to_slack script to post backups to slack.
- create cronjobs to create backup, post to slack and remove
backupfiles from the server.
- create backup folder where backups will be stored.
- create backup script.
N/A
db file uploads are posted on the slack channel  #vof-db-backups at 00:00 EAT daily
N/A
[#158490298](https://www.pivotaltracker.com/story/show/158490298)
N/A
N/A

#158490298 Create db backup script

---

packer/start_vof.sh

- remove heroku url's
- use GKE url's
N/A
N/A
N/A
[#158598863](https://www.pivotaltracker.com/story/show/158598863)
N/A
N/A

#158598863 Fix micro login deployment

---

packer/downtime.sh
packer/packer.json
packer/start_vof.sh
vof_base_image/setup.sh

- create downtime.sh script that will make the reports
- create cronjob to run downtime.sh script every minute
- add imagemagick to the base image dependencies
- add -p flag on creation of backups folder to avoid errors if it
already exists.
- add bc to base image dependencies. bc is a language that supports
arbitrary precision numbers with interactive execution of statements
N/A
N/A
N/A
[#158790623](https://www.pivotaltracker.com/story/show/158790623)
N/A
N/A

#158790623 Script to report known 502 errors

---

.gitignore
terraform/vof/prod/compute.tf
terraform/vof/prod/database.tf
terraform/vof/prod/variables.tf
terraform/vof/staging-sandbox/compute.tf
terraform/vof/staging-sandbox/routing.tf
terraform/vof/staging-sandbox/variables.tf

Remove declared but un-used variables and unnecessary conditional statements since the production environment has separate infrastructure scripts
* Make changes requested in the comment section of [PR 98](https://github.com/andela/vof-deployment-scripts/pull/98)
* Remove declared but un-used variables
* Remove unnecessary variable lookups
* Remove unnecessary conditional statements
Following some changes made in the [network testing PR](https://github.com/andela/vof-deployment-scripts/pull/98), some variables and conditional assignments were no longer needed.
[#161085387](https://www.pivotaltracker.com/story/show/161085387)

#161085387 Clean up Terraform variables

---

packer/start_vof.sh

* Adds `Sidekiq`'s Supervisord Service to complete setup of [learner notification](https://github.com/andela/vof-tracker/pull/1191)
- creates log files for stdout and stderr
- creates Supervisord config for Sidekiq
- add Sidekiq logs to the log-rotate cronjob
* Once this PR is reviewed and merged we can test it by first deploying to the sandbox environment and checking if notifications are working as expected
> Please be advised that this task has been implemented as a hotfix to the current deployment scripts which are shared across all deployment environments. 
As such, during the testing period, and in order to avoid downtime on either `Production` and/or `Staging`, we should probably hold on triggering any deployments until testing is completed successfully.
* This PR is meant to …

#161743895 Add Sidekiq Supervisord service

---

docker/ci/Dockerfile
packer/base/packer.json
packer/base/roles/install-logging-agent/tasks/main.yml
packer/vof/packer.json
packer/vof/playbook.yml
packer/vof/roles/copy-files/tasks/main.yml
packer/vof/roles/setup-filebeat/tasks/main.yml
packer/vof/roles/setup-filebeat/templates/filebeat.yml
packer/vof/roles/setup-fluentd/tasks/main.yml
packer/vof/roles/setup-fluentd/templates/setup_fluentd.sh
packer/vof/roles/setup-metricbeat/tasks/main.yml
packer/vof/roles/setup-metricbeat/templates/metricbeat.yml
packer/vof/roles/setup/tasks/main.yml
packer/vof/start_vof.sh
terraform/vof/staging-sandbox/compute.tf

Refactor how new code is added to the instance using a deploy key
- add ssh keys to base image
- clone repo to base image
- add function to update repo with commit hash
Previously the code with the new changes was being copied from circleci and added to the image while it was being baked which meant that a new image had to be baked every time the code changed. After some deliberation we realised that this was an unnecessary step with financial implications and worked out that it's better if we have one image being used to create instances with the new code being pulled in the start script during the rolling replace.
[#162130134](https://www.pivotaltracker.com/story/show/162130134)

#162130134 Pull commited changes using deploy keys

---

docker/ci/Dockerfile
packer/base/packer.json
packer/base/roles/install-logging-agent/tasks/main.yml
packer/vof/packer.json
packer/vof/playbook.yml
packer/vof/roles/copy-files/tasks/main.yml
packer/vof/roles/setup-filebeat/tasks/main.yml
packer/vof/roles/setup-filebeat/templates/filebeat.yml
packer/vof/roles/setup-fluentd/tasks/main.yml
packer/vof/roles/setup-fluentd/templates/setup_fluentd.sh
packer/vof/roles/setup-metricbeat/tasks/main.yml
packer/vof/roles/setup-metricbeat/templates/metricbeat.yml
packer/vof/roles/setup/tasks/main.yml
packer/vof/start_vof.sh
terraform/vof/staging-sandbox/compute.tf

Changes the image provisioning from using bash scripts to primarily using ansible
- edit docker ci image to include python3 and ansible
- edit base image google-fluentd installation
- edit vof packer file to have ansible as a provisioner
- edit start_vof.sh file to remove setup-scripts functions
- add role for initial vof user setup
- add role to copy files into the image
- add role to setup metricbeat
- add role to setup filebeat
- add role to setup fluentd
Previously, we were provisioning the images with bash scripts and we came to realise they are harder to debug and for new people to onboard onto the team so we decided to change over to using ansible which is easier to work with.
[#161717320](https://www.pivotaltracker.com/story/show/161717320)

#161717320 Provision vof image with ansible

---

packer/start_vof.sh

* adds the sidekiq serveice creator to the  main function
Setup was incomplete and required the function to beadded to the main function.
* Through an SSH connection to the server once the PR is merged
[#162314047](https://www.pivotaltracker.com/story/show/162314047)

#162314047 Fix sidekiq service setup

---

packer/start_vof.sh
vof/routing.tf

Updates the certificate chains to include the missing certificate so we can have a grade A rating on Qualys SSl Labs
Transfer andela_certificate.pem from apprenticeship-projects to vof-tracker project in GCP
Use .pem file instead of '.cert' file for the certificate
After a successful deployment go to https://sslabs.com and test the URL [vof.andela.com](vof.andela.com)
[162643643](https://www.pivotaltracker.com/story/show/162643643)
N/A
N/A

#162643643 use new ssl key to complete the ssl keychain

---

packer/start_vof.sh

Allow the whitelisted IP to access the database instances on GCP
- Add `35.231.177.164` to the whitelist
N/A
[163646189](https://www.pivotaltracker.com/story/show/163646189) [163646484](https://www.pivotaltracker.com/story/show/163646484)
N/A

#163646189 whitelist required IP
