andela/vof-deployment-scripts

packer/start_vof.sh
Changes make supervisord restart, a daily action to counter effects of log rotation which create a new log file that the existing application fails to write to before a restart.
Changes make supervisord restart, a daily action to counter effects of log rotation which create a new log file that the existing application fails to write to before a restart.
N/A
N/A
N/A
N/A
N/A
=> Fixes logging bug that occurs after log rotation

docs/infrastructure.md, packer/start_vof.sh
This P.R adds a new environment on the vof application called sandbox. The environment is used by developers to test changes on their application without having to merge it on the develop branch and view it on staging. It caters for both the design-v2 and develop branch where a developer will follow the workflow on the slide below to trigger a sandbox environment using this script.
https://docs.google.com/presentation/d/16BSxT_o6wJ3ouG8_orFtGoASsCt_Q2rZlmkVXGjFg0Q/edit?usp=sharing
Changes on this script alone:
- The task involved adding a script that could generate a random 64 digit number that would be added to the secrets.yml file of the vof application.
- It also required linking the new sandbox environment to it's own database file with the name vof-sandbox.sql. This file requires to …
=> #154919001: Add a sandbox environment for the developers

packer/start_vof.sh
- add secret key base for the design-v2 environment.
- Use design-v2 resources for design-v2 deployments.
- Add logging for design-v2 deployments.
- This PR adds logging and secrets for the newly created design-v2 environment. It also allows desgin-v2 deployments to use design-v2 resources.
n/a
This PR needs to be merged before [this](https://github.com/andela/vof-tracker/pull/687) PR at vof-tracker is merged to make the deployment work.
#154919385
n/a
=> chore(design-v2-migration): use design-v2 environment

vof-redis-base-image/packer.json, vof-redis-base-image/setup.sh, vof/compute.tf, vof/redis.tf
- Adds packer template and setup script for creation of a base redis server image
- Add infrastructure code to create the image using tf
Navigate to the vof-redis-base-image directory and run
`packer build packer.json`
this will create an image on your GCP project
Then run
`terrafoam plan -out=plan-file`
to create a sequence of events for packer to run
Then run
`terrafoam apply "plan-file"`
to setup the infrastructure online
Ensure the redis_ip tf variable is set to a **reserved global ip** to ensure it works.
Redis servers were previosuly created manually with either the GCP GUI or CLI
[#155931351](https://www.pivotaltracker.com/story/show/155931351)
N/A
N/A
=> #155931351: Automate redis server creation

packer/start_vof.sh, vof/compute.tf, vof/redis.tf
- use external redis server IP for websocket connection
- dynamically authorize environment instances to use redis server
- use port ranges to allow instances reach redis instance
N/A
N/A
The previous fix merged appeared to work only for a short while. This has been more thoroughly tested.
[#155931351](https://www.pivotaltracker.com/story/show/155931351)
N/A
N/A
=>  #155931351: Automate redis server creation (fix #2)

packer/start_vof.sh
Allow execution of the start up script to continue even when dynamic updates fail
N/A
N/A
While replicating the downtime on staging, after doing this, I observed no downtime. The downtime is still a hard one to fix since I can't replicate on andela-learning but this gave a positive test, I'm hoping it will be a lasting solution to the downtime-during-deployments issue.
[#157347094](https://www.pivotaltracker.com/story/show/157347094)
N/A
N/A
=> #157347094:  Ensure dynamic updates don't halt startup script

packer/start_vof.sh
This PR whitelists various IP addresses from the
Kampala, Nairobi and Lagos offices to allow developers
to be able to access the staging db data through a
postgres client.
N/A
N/A
Currently VOF developers need to go through DevOps Engineers to access the staging DB.
[#157184690](https://www.pivotaltracker.com/n/projects/2126505/stories/157184690)
N/A
N/A
=> #157184690: Add KLA, NBO and LAGOS IPs to access staging db

vof/jumpbox.tf, vof/network.tf, vof/redis.tf, vof/routing.tf, vof/variables.tf
- stop autocreation of subnetworks by terraform and instead
opt for creating 2 custom subnets
- put both redis and jumpbox servers under a custom made
subnetwork
- create 2 unique IPv4 address ranges for each environment
- refactor vof internal firewall to allow communication between
IP addresses of defined ranges
N/A
N/A
N/A
[#157913007](https://www.pivotaltracker.com/story/show/157913007)
N/A
N/A
=> 157913007: Refactor network infrastructure

packer/setup-scripts/setup_filebeat.sh, packer/setup-scripts/setup_metricbeat.sh, vof-elk-image/packer.json, vof/variables.tf
- exlude healthcheck logs from being sent
to our elk server to save valuable space
- increase metricbeat period to 60 seconds,
this send logs to elk less often
- change the healthcheck route to '/health'
- increase elk space to 20GB so that its
harder to reach the 85% disk storage
threshold that locks logs from being
received by elastic search
N/A
N/A
N/A
[#158027985](https://www.pivotaltracker.com/story/show/158027985)
N/A
N/A
=> #158027985: Manage VOF application logs

packer/start_vof.sh, vof/compute.tf, vof/variables.tf
- Replaces the slack token used for sending DB backup notifications with a variable.
- Change the token to a variable and set the token in the CircleCI environment variables.
- DB backups are set to be posted everyday to the #vof-db-backups slack channel at 00:00 WAT. Check the channel to see the backup files
[#158793351](https://www.pivotaltracker.com/story/show/158793351)
=> #158793351 Replace slack token for db backups with a variable

packer/start_vof.sh, vof/compute.tf, vof/variables.tf
- Replaces the slack token used for sending DB backup notifications with a variable.
- Change the token to a variable and set the token in the CircleCI environment variables.
- DB backups are set to be posted everyday to the #vof-db-backups slack channel at 00:00 WAT. 
- What are the relevant pivotal tracker stories?
[#158793351](https://www.pivotaltracker.com/story/show/158793351)
=> #158793351 Replace slack token for db backups with a variable (2)

vof/compute.tf
- increase the loadbalancer timeout period to 120 seconds as advised by
the dev team so as to give more time to queries that take longer than
30 seconds to execute. This helps us avoid some 502 errors related to
downloads
N/A
N/A
N/A
[#159105020](https://www.pivotaltracker.com/story/show/159105020)
N/A
N/A
=> #159105020 Increase loadbalancer timeout period

packer/setup-scripts/setup_fluentd.sh, packer/start_vof.sh
Works on leaning out the start-vof.sh script to reduce run failures and eliminate resultant downtime
- removed the google-fluentd setup into a separate script
- added a service to run the config script
N/A
[#159070982](https://www.pivotaltracker.com/story/show/159070982)
N/A
=> #159070982 Breakdown start script

packer/setup-scripts/setup_filebeat.sh, packer/setup.sh, packer/start_vof.sh
This PR fixes a bug that was affecting the installation of filebeat.
Currently filebeat does not install when instances are being spun up due to a process, `unattended upgrades`, that is run automatically on the instance to update security patches, holding up the dpkg database which is also needed for filebeat to install. This stops the services that manage unattended upgrades before filebeat is installed to allow the unattended upgrades to complete and release the dpkg database and restarts them after all the steps in the start script have run.
After deployment, you can look at the bake image workflow logs and see that filebeat has been installed. 
[#159328586](https://www.pivotaltracker.com/story/show/159328586)
=> #159328586 Move filebeat installation to setup script and manage unattended upgrades

packer/setup-scripts/setup_filebeat.sh, packer/setup.sh, packer/start_vof.sh
This PR fixes a bug that was affecting the installation of filebeat.
Currently filebeat does not install when instances are being spun up due to a process, unattended upgrades, that is run automatically on the instance to update security patches, holding up the dpkg database which is also needed for filebeat to install. This stops the services that manage unattended upgrades before filebeat is installed to allow the unattended upgrades to complete and release the dpkg database and restarts them after all the steps in the start script have run.
After deployment, you can look at the bake image workflow logs and see that filebeat has been installed.
[#159328586](https://www.pivotaltracker.com/story/show/159328586)
=> #159328586 Move filebeat installation to setup script and manage unattended upgrades (2)

packer/setup-scripts/setup_metricbeat.sh, packer/setup.sh, packer/start_vof.sh, vof_base_image/setup.sh
This PR moves the filebeat and metricbeat installations to the `vof base image`.
- Move install filebeat and metricbeat functions to the `vof base image` setup.sh
- Remove metricbeat installation step from the start_vof.sh
- Remove the install filebeat function from the setup_metricbeat.sh
- Remove filebeat installation from the `vof image` setup.sh
- Remove the restart unattended upgrades from start-script
Currently metricbeat installation fails when instances are being spun up due to a process, unattended upgrades, that is run automatically on the instance to update security patches, holding up the dpkg database which is also needed for metricbeat to install. This is similar to an issue we were having with filebeat. It was solved by moving the installation to the `bake image` step in …
=> #159734041 Move filebeat and metric installations to the base image

vof_base_image/setup.sh
- Adds ImageMagick
- Adds bc
The above dependencies are added to solve a bug/error caught by BugSnag. Follow this [link](https://app.bugsnag.com/andela/vof-tracker-production/errors/5b770163d0d27a0019f17464?event_id=5b796ef1002acb6b5e310000&i=sk&m=oc) for details.
Seeing as the base image has been updated with the changes on GCP all new deployments won't have this issue.
[#159861943](https://www.pivotaltracker.com/story/show/159861943)
[#159861904](https://www.pivotaltracker.com/story/show/159861904)
=> #159861943 Add ImageMagick to base image 

packer/setup-scripts/setup_metricbeat.sh, packer/start_vof.sh, vof_base_image/setup.sh
This PR moves the filebeat and metricbeat installations to the `vof base image`.
- Move install filebeat and metricbeat functions to the` vof base image` setup.sh
- Remove metricbeat installation step from the start_vof.sh
- Remove the install filebeat function from the setup_metricbeat.sh
- Remove filebeat installation from the `vof image` setup.sh
- Remove the restart unattended upgrades from start-script
Currently, metricbeat installation fails when instances are being spun up due to a process, unattended upgrades, that is run automatically on the instance to update security patches, holding up the dpkg database which is also needed for metricbeat to install. This is similar to an issue we were having with filebeat. It was previously solved by moving the installation to the `bake …
=> #159734041 Move filebeat and metric installations to the base image (2)

packer/delete_images.sh, packer/packer.json, packer/start_vof.sh
Adds a cronjob running a script every first of the month to delete unused images from GCP
- Add a script that deletes unused images
- Add a cronjob that calls the script every 1st of the month
- Add the delete_images.sh script to the /home/vof directory
Whenever a deployment happens, a new image is created with the new code and pushed to GCP, and the new image is used to run the app, after a few deployments, these images accumulate but only 2 of them are necessary, the one that is currently being used to run the app and the last previously used image in case we want to rollback. GCP charges for all each custom image so if it is not being used it should be deleted to avoid incurring unnecessary charges.
[#159863633](https://www.pivotaltracker.com/story/show/159863633)
=> #159863633 Add cronjob to delete unused images

packer/downtime.sh, packer/packer.json, packer/start_vof.sh
Fixes an issue with the implementation of 502 error reporting that led to downtime when the task was previously merged.
- add the downtime script for picking up down 502 errors
- add cronjob to report 502 errors every minutes
- add provisioner to add the dowtime script to the /home/vof dir
- add a parents flag to the post backups function mkdir command
[#158790623](https://www.pivotaltracker.com/story/show/158790623) [#159848993](https://www.pivotaltracker.com/story/show/159848993)
=>  #158790623 Fix issue with 502 errors reporting implementation

vof_base_image/setup.sh
- Adds ImageMagick
- Adds bc
The above dependencies are added to solve a bug/error caught by BugSnag. Follow this [link](https://app.bugsnag.com/andela/vof-tracker-production/errors/5b770163d0d27a0019f17464?event_id=5b796ef1002acb6b5e310000&i=sk&m=oc) for details.
Seeing as the base image has been updated with the changes on GCP all new deployments won't have this issue.
[#159861943](https://www.pivotaltracker.com/story/show/159861943)
[#159861904](https://www.pivotaltracker.com/story/show/159861904)
=> ch(dependencies) add imagemagick and bc to base image

packer/delete_images.sh, packer/packer.json, packer/start_vof.sh
Adds a cronjob running a script every first of the month to delete unused images from GCP
- Add a script that deletes unused images
- Add a cronjob that calls the script every 1st of the month
- Add the delete_images.sh script to the /home/vof directory
Whenever a deployment happens, a new image is created with the new code and pushed to GCP, and the new image is used to run the app, after a few deployments, these images accumulate but only 2 of them are necessary, the one that is currently being used to run the app and the last previously used image in case we want to rollback. GCP charges for all each custom image so if it is not being used it should be deleted to avoid incurring unnecessary charges.
[#159863633](https://www.pivotaltracker.com/story/show/159863633)
=> #159863633 Add cronjob to delete unused images (2)

packer/downtime.sh, packer/packer.json, packer/start_vof.sh
Fixes an issue with the implementation of 502 error reporting that led to downtime when the task was previously merged.
add the downtime script for picking up down 502 errors
add cronjob to report 502 errors every minutes
add provisioner to add the dowtime script to the /home/vof dir
add a parents flag to the post backups function mkdir command
[#158790623](https://www.pivotaltracker.com/story/show/158790623) [#159848993](https://www.pivotaltracker.com/story/show/159848993)
=> #158790623 Fix issue with 502 errors reporting implementation (2)

vof-elk-image/start_elk.sh
Adds a cronjob for a daily routine of unlocking the kibana instance for receiving the logs from the 
- Creates a file under the directory '/etc/cron.daily/unlock-kibana-logs`
- Configure the file to run daily by placing it under the `cron.daily` directory
Kibana stays read only when ES high disk watermark has been exceeded and later gone beneath the limit. For this reason, we are not able to access the most recent logs from vof applications. i.e vof-staging, vof-sandbox, vof-production. 
In case we want to update the instance, the unlocking has to be done manually.
[2126505](https://www.pivotaltracker.com/story/show/160239422) 
[160239584](https://www.pivotaltracker.com/story/show/160239584)
=> creates a function to add a cronjob

packer/start_vof.sh
Changes the time when the unattended upgrades are triggered by a cronjob to run
- change the day and time when the unattended upgrades cronjob runs from Friday morning to Sunday morning
Currently the unattended upgrades are manually triggered by a cronjob on Friday however that uses up a lot of the resources on the instances and this is not ideal as it limits the amount of resources available to handle the users tasks
[#159874326](https://www.pivotaltracker.com/story/show/159874326) [#159874322](https://www.pivotaltracker.com/story/show/159874322)
=> #159874326 Change when unattended upgrades run

vof/database.tf
Fix the error currently being experienced when orchestrating the vof infrastructure. This is incompatibility issue with postgres bunary logs as seen on the image below
- Change the value of `binary_logs_anabled` to `false`
- Change the value mentioned above.
- Point the the environment variable in circleCI `VOF_INFRASTRUCTURE_REPO` the repo that changed the value and trigger a build.
N/A
[160366251](https://www.pivotaltracker.com/story/show/160366251)
N/A
=> change binary logs param to false

vof/main.tf
- set the GCP provider version to 1.17
Set the version of the GCP provider to v1.17
Terraform upgraded the gcp provider and the upgrade introduced a bug which changed the way that the instance templates pick up the application images
[#160633743](https://www.pivotaltracker.com/story/show/160633743) [160633876](https://www.pivotaltracker.com/story/show/160633876)
=> #160633876 Set terraform gcp provider version to 1.17

utilities/redis_replication_setup.sh
- Adds Redis replication automation script
For faster, more efficient and scalable Redis setup, this PR adds a simple replication setup script.
1. Create a testing cluster: you can use Minikube locally
2. Deploy the Redis StatefulSet app to the cluster with the manifests in the `k8s/redis/` folder
3. `cd` into *utilities* directory and execute run either of the commands below
```bash
$ ./redis_replication_setup main
```
or
```bash
$ ./redis_replication_setup assign_replicas
```
[#162393139](https://www.pivotaltracker.com/story/show/162393139)
=> #162393139 Add redis replica setup script

packer/backup_to_gcp.sh, packer/packer.json, packer/seed_prod_backup_to_staging.sh, packer/start_vof.sh, vof_base_image/packer.json
Create a cronjob that seeds production database to staging database after every 2 weeks.
- Create a cronjob that sends the database dump to gcp bucket
- Edit the dump file to include the required parameters for a successful import to take place.
- Create a cronjob that pulls the db dump- backed up production dump- from staging environment.
- Import the database dump into the staging environment
- `clone` this repo
- `git checkout ft-cronjob-seed-staging-production-db-162951188`
- To make sure you don't wait for 2 weeks to test this, change the file `packer/start_vof.sh` on line 121 and use a considerable time. for example after 1 hour or 30 mins.
That would look something like this, 
`30 * * * * && /bin/bash /home/vof/backup_to_gcp.sh` 
- Also, change the time for the scheduled db import. …
=> #162951188 Seed staging db with production db

packer/start_vof.sh
Fixes the syntax error in one of the functions since the error is causing deployment failures.
* corrected the syntax error in the conditional statement on the database backup management functionality.
* Once this PR is merged, the error in [the screenshot below](https://user-images.githubusercontent.com/30072633/52050766-aa8e8380-2562-11e9-99ce-6db9bf1df4ad.png) should desist.
* There were some additions to the database backup management section of the start_up.sh script that had syntax error that we'd missed. This was and remains to be a rare oversight on our part and should never occur again.
[#163619583](https://www.pivotaltracker.com/story/show/163619583)
=> #163619583 Fixes syntax error in start_up script

packer/start_vof.sh
* Fixes the semantic error in one of the functions since the error is causing deployment failures.
* Fixed the addition of the database management cron jobs.
* The start_up script should execute to completion without error.
* This work is continued from a similar PR meant to address a [syntax error](https://github.com/andela/vof-deployment-scripts/pull/120) in the script.
[#163619583](https://www.pivotaltracker.com/story/show/163619583)
=> #163619583 Fix semantic error in start_up script

packer/start_vof.sh
- rename the database hostname
- change permissions on backup-to-staging script
- change permissions on seed-staging-db-with-prod
After merge, head over to GCP and check the serial logs for the application on production. If the error shown below is not there, it has been fixed
N/A
[163649781](https://www.pivotaltracker.com/story/show/163649781)
[163650108](https://www.pivotaltracker.com/story/show/163650108)
=> #163649781 fix database reference error.
